cloud:
  aws:
    credentials:
      access-key: YCAJEPZqFRbSrmQoIny1StwFI
      secret-key: YCOxa5vGW9uSX1sdJSsUj6ucavUR3TCib7hALMBE
    region:
      static: ru-central1

application:
  bucket:
    name: komelin.photo.saver.storage